let items = {
    item: [
        {
            id: 1,
            name: "Araña Gelatinosa",
            description: "Consigue esta araña gelatinosa, excelente para decorar tus islas de Halloween! 🕷️",
            price: 2000,
            coinType: "gold",
            image: "arana.png",
            itemType: "Rare",
        },
        {
            id: 2,
            name: "Egg Bohemio",
            description: "Consigue este increible huevo artista de pascua! 🎨",
            price: 5000,
            coinType: "gold",
            image: "bohemio_by_ariel.png",
            itemType: "Casi unico",
        },
        {
            id: 3,
            name: "Coldman",
            description: "Consigue este asombroso hombre de hielo y decora tus islas con un toque friolento! 🥶",
            price: 2500,
            coinType: "gold",
            image: "coldman_by_ariel.png",
            itemType: "Normal",
        },
        {
            id: 4,
            name: "Egg Nuwa",
            description: "Consigue este increible huevo bañado en bronce y con una increible estrella! ⭐",
            price: 8000,
            coinType: "silver",
            image: "nuwa_by_ariel.png",
            itemType: "Muy rare",
        },
        {
            id: 5,
            name: "Octopus",
            description: "Consigue este tierno y dulce pulpo, capaz de conmover a todo le que lo vea! 🐙",
            price: 3000,
            coinType: "gold",
            image: "pulpo_high_quality_by_ariel.png",
            itemType: "Rare",
        },
        {
            id: 6,
            name: "Love Tree",
            description: "Consigue este arbol de sanvalentin que ademas funciona como un teletransportador! 💖",
            price: 1000,
            coinType: "gold",
            image: "lovetree.png",
            itemType: "Normal",
        },
        {
            id: 7,
            name: "Egg Music Cholo",
            description: "Consigue este asombroso huevo reproductor de musica, cada uno contiene canciones diferentes! 🎵",
            price: 5000,
            coinType: "silver",
            image: "egg_music_cholo_by_ariel.png",
            itemType: "Normal",
        },
        {
            id: 8,
            name: "Egg Music Jaguar",
            description: "Consigue este huevo reproductor de musica, cada uno contiene canciones diferentes!",
            price: 5000,
            coinType: "silver",
            image: "egg_music_jaguar_by_ariel.png",
            itemType: "Normal",
        },
        {
            id: 9,
            name: "Ghost",
            description: "Consigue este increible fantasma y espanta a todo el que entre a tu isla! 👻",
            price: 1500,
            coinType: "gold",
            image: "ghost_1_by_ariel.png",
            itemType: "Rare",
        },
        {
            id: 10,
            name: "Frankling Egg",
            description: "Consigue este increible huevo electromecanico que funciona como una bobina de tesla! ⚡",
            price: 8000,
            coinType: "gold",
            image: "FRANKLING_EGG_by_ariel.png",
            itemType: "Unico",
        },
        {
            id: 11,
            name: "Sea Egg",
            description: "Consigue este increible huevo que se ha infestado de diferentes criaturas marinas durante todo es tiempo! 🌊",
            price: 5000,
            coinType: "gold",
            image: "sea_egg_by_ariel.png",
            itemType: "Rare",
        },
        {
            id: 12,
            name: "Dino Lee",
            description: "Consigue este increible dinosaurio que ademas es un experto en las artes marciales! 🦖",
            price: 3000,
            coinType: "gold",
            image: "DinoLee_by_ariel.png",
            itemType: "Muy rare",
        },
        {
            id: 13,
            name: "Egg Dissey",
            description: "Consigue este increible huevo a punto de convertirse! 🐥",
            price: 10000,
            coinType: "gold",
            image: "Egg_dissey_by_ariel.png",
            itemType: "Casi unico",
        },
        {
            id: 14,
            name: "Raregalo",
            description: "Consigue este increible regalo, abrelo y mira que contiene, puedes encontrar hasta 5 objetos raros! 🎁",
            price: 7000,
            coinType: "gold",
            image: "Raregalo_by_ariel.png",
            itemType: "Rare",
        },
    ],
}

export {items};